In [1]:
# Importing libraries.

import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [2]:
avg_scores = pd.read_csv('input_data/naep.csv')
poverty_income = pd.read_csv('input_data/poverty_income.csv')
unemploy_crime = pd.read_csv('input_data/unemployment_crime.csv')

In [3]:
unemploy_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459 entries, 0 to 458
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   year                 459 non-null    int64  
 1   state                459 non-null    object 
 2   unemployment_rate    459 non-null    float64
 3   violent_crime_rate   459 non-null    float64
 4   property_crime_rate  459 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 18.1+ KB


In [4]:
merged_df = pd.merge(avg_scores, poverty_income, how = 'left' , left_on =['state', 'year'], right_on=['state', 'year'])
merged_df = pd.merge(merged_df, unemploy_crime, how = 'left' , left_on =['state', 'year'], right_on=['state', 'year'])
merged_df

year          state   avg_score      subject  grade  poverty_percent  \
0     2019        Alabama  268.703899  Mathematics      8             15.6   
1     2019         Alaska  274.337801  Mathematics      8             10.2   
2     2019        Arizona  279.932022  Mathematics      8             13.5   
3     2019       Arkansas  274.363192  Mathematics      8             16.0   
4     2019     California  275.608909  Mathematics      8             11.8   
...    ...            ...         ...          ...    ...              ...   
1831  2003       Virginia  223.340359      Reading      4             10.0   
1832  2003     Washington  221.096695      Reading      4             11.0   
1833  2003  West Virginia  219.179525      Reading      4             16.3   
1834  2003      Wisconsin  220.833428      Reading      4              8.9   
1835  2003        Wyoming  222.075166      Reading      4             10.8   

      median_income  unemployment_rate  violent_crime_rate  \
0             51771                3.0              504.67   
1             77203                5.4              865.05   
2             62027                4.9              447.12   
3             49020                3.5              580.84   
4             80423                4.2              442.07   
...             ...                ...                 ...   
1831          50028                4.1              278.20   
1832          48185                7.4              346.94   
1833          32967                6.0              255.43   
1834          46538                5.7              221.11   
1835          41554                4.3              261.70   

      property_crime_rate  
0                 2622.80  
1                 2902.52  
2                 2435.98  
3                 2847.71  
4                 2335.78  
...                   ...  
1831              2721.54  
1832              4754.98  
1833              2339.02  
1834              2880.45  
1835              3315.60  

[1836 rows x 10 columns]

## Neural Network Testing - Grade 8 Math

In [5]:
math_merged_df = merged_df.loc[(merged_df['subject'] == 'Mathematics')]
math_8_merged_df = math_merged_df.loc[(merged_df['grade'] == 8)]
math_8_merged_df

year          state   avg_score      subject  grade  poverty_percent  \
0    2019        Alabama  268.703899  Mathematics      8             15.6   
1    2019         Alaska  274.337801  Mathematics      8             10.2   
2    2019        Arizona  279.932022  Mathematics      8             13.5   
3    2019       Arkansas  274.363192  Mathematics      8             16.0   
4    2019     California  275.608909  Mathematics      8             11.8   
..    ...            ...         ...          ...    ...              ...   
454  2003       Virginia  281.676643  Mathematics      8             10.0   
455  2003     Washington  281.151364  Mathematics      8             11.0   
456  2003  West Virginia  270.770353  Mathematics      8             16.3   
457  2003      Wisconsin  283.915866  Mathematics      8              8.9   
458  2003        Wyoming  283.503350  Mathematics      8             10.8   

     median_income  unemployment_rate  violent_crime_rate  property_crime_rate  
0            51771                3.0              504.67              2622.80  
1            77203                5.4              865.05              2902.52  
2            62027                4.9              447.12              2435.98  
3            49020                3.5              580.84              2847.71  
4            80423                4.2              442.07              2335.78  
..             ...                ...                 ...                  ...  
454          50028                4.1              278.20              2721.54  
455          48185                7.4              346.94              4754.98  
456          32967                6.0              255.43              2339.02  
457          46538                5.7              221.11              2880.45  
458          41554                4.3              261.70              3315.60  

[459 rows x 10 columns]

In [6]:
math_8_merged_df = math_8_merged_df.drop(columns = 'year')
math_8_merged_df = math_8_merged_df.drop(columns = 'state')
math_8_merged_df = math_8_merged_df.drop(columns = 'subject')
math_8_merged_df = math_8_merged_df.drop(columns = 'grade')
math_8_merged_df = math_8_merged_df.drop(columns = 'violent_crime_rate')
math_8_merged_df = math_8_merged_df.drop(columns = 'property_crime_rate')
math_8_merged_df

avg_score  poverty_percent  median_income  unemployment_rate
0    268.703899             15.6          51771                3.0
1    274.337801             10.2          77203                5.4
2    279.932022             13.5          62027                4.9
3    274.363192             16.0          49020                3.5
4    275.608909             11.8          80423                4.2
..          ...              ...            ...                ...
454  281.676643             10.0          50028                4.1
455  281.151364             11.0          48185                7.4
456  270.770353             16.3          32967                6.0
457  283.915866              8.9          46538                5.7
458  283.503350             10.8          41554                4.3

[459 rows x 4 columns]

In [7]:
math_8_merged_df.isnull().sum()

avg_score            0
poverty_percent      0
median_income        0
unemployment_rate    0
dtype: int64

In [8]:
math_8_merged_df.describe()

avg_score  poverty_percent  median_income  unemployment_rate
count  459.000000       459.000000     459.000000         459.000000
mean   281.063339        13.500000   52867.071895           5.681481
std      8.060094         3.217603   10893.021072           2.113221
min    243.059638         6.400000   32397.000000           2.300000
25%    276.552224        10.900000   44802.500000           4.100000
50%    282.100610        13.100000   51086.000000           5.200000
75%    286.415051        15.850000   59447.000000           6.900000
max    300.568235        23.900000   90395.000000          13.700000

In [9]:
bins = [0, 250.9, 265.9, 280.9, 305]
group_names = [0, 1, 2, 3]
math_8_merged_df['new_col'] = pd.cut(math_8_merged_df['avg_score'],bins, labels=group_names, include_lowest=True)

In [10]:
math_8_merged_df = math_8_merged_df.drop(columns = 'avg_score')
math_8_merged_df

poverty_percent  median_income  unemployment_rate new_col
0               15.6          51771                3.0       2
1               10.2          77203                5.4       2
2               13.5          62027                4.9       2
3               16.0          49020                3.5       2
4               11.8          80423                4.2       2
..               ...            ...                ...     ...
454             10.0          50028                4.1       3
455             11.0          48185                7.4       3
456             16.3          32967                6.0       2
457              8.9          46538                5.7       3
458             10.8          41554                4.3       3

[459 rows x 4 columns]

In [11]:
x = math_8_merged_df.drop(columns = 'new_col').values
y = math_8_merged_df['new_col'].values

In [12]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

y = tf.keras.utils.to_categorical(y)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.05, random_state = 42)
print(x_test)

[[1.5700e+01 5.1063e+04 5.4000e+00]
 [9.1000e+00 8.5786e+04 3.4000e+00]
 [1.1700e+01 6.2745e+04 5.7000e+00]
 [8.9000e+00 5.6356e+04 5.8000e+00]
 [1.0100e+01 7.0058e+04 7.0000e+00]
 [1.1600e+01 6.3126e+04 7.3000e+00]
 [1.8000e+01 3.3466e+04 5.1000e+00]
 [1.4200e+01 4.5048e+04 4.9000e+00]
 [2.0500e+01 4.1804e+04 7.8000e+00]
 [1.9900e+01 4.3595e+04 5.1000e+00]
 [1.3500e+01 3.7925e+04 5.6000e+00]
 [1.5800e+01 4.1551e+04 4.1000e+00]
 [1.0700e+01 5.9913e+04 2.9000e+00]
 [1.4100e+01 4.3000e+04 3.6000e+00]
 [1.4100e+01 4.8188e+04 4.7000e+00]
 [1.7500e+01 4.3215e+04 6.8000e+00]
 [1.0800e+01 6.5822e+04 8.8000e+00]
 [1.3600e+01 5.5802e+04 6.7000e+00]
 [1.0600e+01 4.2952e+04 5.7000e+00]
 [1.5600e+01 5.1771e+04 3.0000e+00]
 [1.1300e+01 5.5980e+04 3.4000e+00]
 [1.1200e+01 5.6985e+04 8.3000e+00]
 [8.9000e+00 4.6538e+04 5.7000e+00]]


In [13]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

In [14]:
input_features = len(x_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 35
hidden_layer3 = 10

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units = hidden_layer1, input_dim = input_features, activation = 'relu'))

nn.add(tf.keras.layers.Dense(units = hidden_layer2, activation = 'relu'))

nn.add(tf.keras.layers.Dense(units = hidden_layer3, activation = 'relu'))

nn.add(tf.keras.layers.Dense(units = 4, activation = 'softmax'))

nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                200       
                                                                 
 dense_1 (Dense)             (None, 35)                1785      
                                                                 
 dense_2 (Dense)             (None, 10)                360       
                                                                 
 dense_3 (Dense)             (None, 4)                 44        
                                                                 
Total params: 2,389
Trainable params: 2,389
Non-trainable params: 0
_________________________________________________________________


In [15]:
nn.compile(loss="categorical_crossentropy", optimizer= "adam", metrics=['accuracy'])

In [16]:
fit_model = nn.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
14/14 [==============================] - 1s 2ms/step - loss: 1.3298 - accuracy: 0.2729
Epoch 2/100
14/14 [==============================] - 0s 4ms/step - loss: 1.1408 - accuracy: 0.4977
Epoch 3/100
14/14 [==============================] - 0s 4ms/step - loss: 0.9791 - accuracy: 0.6628
Epoch 4/100
14/14 [==============================] - 0s 5ms/step - loss: 0.8584 - accuracy: 0.6835
Epoch 5/100
14/14 [==============================] - 0s 4ms/step - loss: 0.7829 - accuracy: 0.6858
Epoch 6/100
14/14 [==============================] - 0s 4ms/step - loss: 0.7428 - accuracy: 0.6881
Epoch 7/100
14/14 [==============================] - 0s 3ms/step - loss: 0.7205 - accuracy: 0.6789
Epoch 8/100
14/14 [==============================] - 0s 4ms/step - loss: 0.7075 - accuracy: 0.6835
Epoch 9/100
14/14 [==============================] - 0s 4ms/step - loss: 0.6956 - accuracy: 0.6858
Epoch 10/100
14/14 [==============================] - 0s 4ms/step - loss: 0.6886 - accuracy: 0.6904
Epoch 11/

14/14 [==============================] - 0s 5ms/step - loss: 0.4994 - accuracy: 0.7706
Epoch 84/100
14/14 [==============================] - 0s 4ms/step - loss: 0.5102 - accuracy: 0.7546
Epoch 85/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5059 - accuracy: 0.7592
Epoch 86/100
14/14 [==============================] - 0s 3ms/step - loss: 0.4950 - accuracy: 0.7615
Epoch 87/100
14/14 [==============================] - 0s 3ms/step - loss: 0.4950 - accuracy: 0.7615
Epoch 88/100
14/14 [==============================] - 0s 3ms/step - loss: 0.4934 - accuracy: 0.7706
Epoch 89/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5004 - accuracy: 0.7615
Epoch 90/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4983 - accuracy: 0.7615
Epoch 91/100
14/14 [==============================] - 0s 4ms/step - loss: 0.4929 - accuracy: 0.7592
Epoch 92/100
14/14 [==============================] - 0s 4ms/step - loss: 0.4885 - accuracy: 0.7638
Epoch 93/100


In [22]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_train_scaled,y_train,verbose=2)

print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

14/14 - 0s - loss: 0.4762 - accuracy: 0.7729 - 44ms/epoch - 3ms/step
Loss: 0.4762461483478546, Accuracy: 0.7729358077049255


In [25]:
# x = tf.convert_to_tensor(x_test)
# input = [[10.2, 77203, 5.4]]
# predictions = nn.predict(x)

# print(predictions)

input = [[70, 10000, 70]]
predictions = nn.predict(input)
print(predictions)

[[0. 1. 0. 0.]]


In [19]:
# nn.save('grade_8_math_model.h5')